export class House {
  id: number = 0;
  water: string = "";
  gas: string = "";
  electricity: string = "";
  sewer: string = "";
  walls: string = "";
  condition: string = "";
  roof: string = "";
  floor: string = "";
  levelCount: number = 0;
  hasGarage: boolean = false;
  hotWater: string = "";
  heating: string = "";
  bath: string = "";
  bathroom: string = "";
  roomCount: number = 0;
  area: number = 0;
  kitchenArea: number = 0;
  landArea: number = 0;
}
